# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
        region = "ap-northeast-2"
        
        assume_role {
            role_arn = "arn:aws:iam::182024812696:role/TerraformAssumedRole"
        }
    }
