# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    assume_role = {
      role_arn = "arn:aws:iam::182024812696:role/TerraformAssumedRole"
    }
    bucket  = "dk-state-bucket"
    encrypt = false
    key     = "test-2/terraform.tfstate"
    region  = "ap-northeast-2"
  }
}
